[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200

[[redirects]]
  from = "/media/*"
  to = "/.netlify/functions/media/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/data/:splat"
  status = 200